gobgp:
  build: ./gobgp/
  ports:
    - 179:179
  links:
    - mongo
  volumes_from:
    - data
  restart: always

# mongo:
#   build: ./mongo/
#   expose:
#     - 27017
#   volumes_from:
#     - data

flask:
  build: ./flask/
  ports:
    - 80:80
  links:
    - mongo
  volumes_from:
    - data

data:
  image: ubuntu:14.04
  volumes:
    - ./flask/app:/var/www/app
    - ./flask/app/log:/var/log/uwsgi/app
    - .:/var/tmp
  command: "true"
